# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="audio.mp3"
Content-Type: audio/mpeg

< ./audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/987254f1-838d-4ca3-aec9-d910793d9420/transcription
Content-Type: application/json

{
  "prompt": "india"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "987254f1-838d-4ca3-aec9-d910793d9420",
  "temperature": 0.5,
  "template": "Do que se trata a transcrição do vídeo? Insira a seguir: '''{transcription}'''"
}