# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="audio.mp3"
Content-Type: audio/mpeg

< ./audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/efaa3175-2dc5-4723-94df-85267b6d686c/transcription
Content-Type: application/json

{
  "prompt": "faz u L"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "efaa3175-2dc5-4723-94df-85267b6d686c",
  "temperature": 0.5,
  "template": "Do que se trata a transcrição do vídeo? Insira a seguir: '''{transcription}'''"
}